apiVersion: v1
kind: ReplicationController
metadata: 
  name: myapp2
  labels: 
    run-redis: three-time
spec:
  replicas: 3
  template:
    metadata:
      name: myapp
      labels:
        labels: myapp-label
    spec: 
      containers:
      - name: redis-app
        image: redis