apiVersion: v1
kind: ReplicationController
metadata: 
  name: myapp3
spec:
  replicas: 2
  template:
    metadata: 
      name: new-app
      labels: 
        name: redis-lal
    spec: 
      containers: 
        - name: redis-app
          image: redis