apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
spec:
  replicas: 3
  template:
    metadata:
      name: myapp-redis
      labels:
        app: myapp-redis-data
    spec:
      containers:
        - name: redis-container
          image: redis
        