apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend4
  labels:
      app: guestbook
      tier: frontend4
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend4
  template:
    metadata:
      labels:
        tier: frontend4
    spec:
      containers:
        - name: nginx-container
          image: nginx

